apiVersion: v1
kind: Service
metadata:
  name: {{ include "openeo-argo.fullname" . }}-postgresql
  labels:
    {{- include "openeo-argo.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: postgresql
    protocol: TCP
    name: postgresql
  selector:
    {{- include "openeo-argo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openeo-argo.fullname" . }}-postgresql-hl
  labels:
    {{- include "openeo-argo.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 5432
    targetPort: postgresql
    protocol: TCP
    name: postgresql
  selector:
    {{- include "openeo-argo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql